# Generated by Django 5.0.3 on 2024-03-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prod_name", models.CharField(max_length=200)),
                ("prod_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("prod_description", models.TextField()),
                ("createAt", models.DateTimeField()),
            ],
        ),
    ]
