# Generated by Django 5.0.3 on 2024-03-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="prod_imgUrl",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
