# Generated by Django 5.0.4 on 2024-04-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0002_produto_prod_imgurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Influencer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inf_name", models.CharField(max_length=200)),
                ("inf_at", models.CharField(max_length=70)),
                ("inf_store_name", models.CharField(max_length=200)),
                ("createAt", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ProdutoInfluencer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_app.influencer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_app.produto",
                    ),
                ),
            ],
        ),
    ]
