# Generated by Django 5.0.4 on 2024-04-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0003_categoria_influencer_produtoinfluencer"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencer",
            name="produtos",
            field=models.ManyToManyField(to="site_app.produto"),
        ),
        migrations.AddField(
            model_name="produto",
            name="prod_categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="site_app.categoria",
            ),
        ),
        migrations.DeleteModel(
            name="ProdutoInfluencer",
        ),
    ]
