# Generated by Django 5.0.3 on 2024-04-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_remove_venda_vend_influencer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
