# Generated by Django 5.0.3 on 2024-04-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_alter_produto_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstName', models.CharField(max_length=20)),
                ('user_lastName', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
