# Generated by Django 5.0.3 on 2024-04-13 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='vend_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.usuario'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
