# Generated by Django 5.0.4 on 2024-05-05 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_venda_vend_cliente_alter_influencer_createdat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='vend_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='influencer',
            name='mainColor',
            field=models.CharField(default='Orange', max_length=15),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cat_name',
            field=models.CharField(choices=[('Vestidos', 'Vestidos'), ('Saias', 'Saias'), ('Calcas', 'Calças'), ('Saias', 'Saias'), ('Shots', 'Shorts')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
