# Generated by Django 5.0.4 on 2024-05-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_alter_venda_vend_cliente_influencer_maincolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cat_name',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='ProdutoInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.influencer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.produto')),
            ],
        ),
    ]
