# Generated by Django 5.0.4 on 2024-05-23 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=11111111111, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dt_nascimento',
            field=models.DateField(default=datetime.date(1999, 10, 17), verbose_name='Data de Nascimento'),
        ),
    ]
