# Generated by Django 5.0.4 on 2024-05-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_alter_usuario_cpf_alter_usuario_dt_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
