# Generated by Django 5.0.4 on 2024-05-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0014_alter_usuario_dt_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('limite_cri', models.IntegerField(null=True)),
                ('limite_adu', models.IntegerField(null=True)),
                ('limite_bebe', models.IntegerField(null=True)),
                ('limite_animal', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Data de inicio')),
                ('fim', models.DateField(verbose_name='Data de saida')),
                ('qtd_crianca', models.IntegerField(null=True)),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.nivel')),
                ('fk_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.produto2')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.produto2')),
                ('fk_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.tag')),
            ],
        ),
        migrations.AddField(
            model_name='produto2',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.tipo'),
        ),
    ]
