# Generated by Django 5.0.4 on 2024-04-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0005_rename_createat_influencer_createdat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="vend_influencer",
        ),
        migrations.RemoveField(
            model_name="venda",
            name="vend_produto",
        ),
        migrations.RemoveField(
            model_name="venda",
            name="vend_quantidade",
        ),
        migrations.CreateModel(
            name="ProdutosVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "influencers",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_app.influencer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_app.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="site_app.venda"
                    ),
                ),
            ],
        ),
    ]
