# Generated by Django 5.0.6 on 2024-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("prod_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
